# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as 
# well as the filename.
# timezone =

# max characters of rev {id} to use in file names
# truncate_slug_length = 40

# set to 'true' to run the environment during 
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without 
# a source .py file to be detected as revisions in the 
# versions/ directory
# sourceless = false

# version location specification; This defaults 
# to alembic/versions.  When using multiple version 
# directories, initial revisions must be specified with 
# --version-path
# version_locations = %(here)s/bar %(here)s/bat alembic/versions

# the version of the (unnamed) environment to use when
# scanning for migrations.  The default is 'main'.
# version_path_separator = :

# set to 'true' to search for scripts recursively
# recursive_version_search = false

# the output encoding used when writing new migration files
# output_encoding = utf-8

sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks allows scripts to be run after generating a migration file
# hooks = ruff
# ruff.type = console_scripts
# ruff.entrypoint = ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
